export interface AnatomyTerm {
  zh: string;
  source: string;
  sourceTerm: string;
  note?: string;
}

import { FUDAN_BATCH_1_TERMS } from './anatomy-terms-fudan-batch-1.ts';

const NAER_DATASET = "https://data.gov.tw/en/datasets/14549";
const simplifiedNote = "已逐条核对 NAER 记录；繁体字形已转为简体中文。";
const modernizedNote = "已逐条核对 NAER 记录；已按当前中国大陆解剖学词序规范化。";
const TA2_SOURCE = "https://libraries.dal.ca/Fipat/ta2.html";
const MAINLAND_TERMS = "https://xtjp.fudan.edu.cn/Upload/Files/201804100314393640155.pdf";
const bridged = (zh: string, ta2Id: number, english: string, latin: string, row: number, sourceChinese: string): AnatomyTerm => ({
  zh,
  source: TA2_SOURCE,
  sourceTerm: `TA2 ${ta2Id}: ${english} / ${latin}; NAER row ${row}: ${sourceChinese}`,
  note: `已将 FIPAT TA2 公共领域术语桥接与 NAER ${NAER_DATASET} 逐条核对；中文字形已规范化。`,
});
const mainlandBridged = (zh: string, entry: string, page: number, ta2Id: number, english: string, latin: string, row: number, sourceLatin: string, sourceChinese: string): AnatomyTerm => ({
  zh,
  source: `${MAINLAND_TERMS}#page=${page}`,
  sourceTerm: `大陆术语 ${entry}: ${zh}; TA2 ${ta2Id}: ${english} / ${latin}; NAER row ${row}: ${sourceLatin} — ${sourceChinese}`,
  note: "已核对 FIPAT TA2、NAER 记录及复旦大学托管的《人体解剖学名词》参考副本；未宣称专业审校。",
});
const mainlandDirect = (zh: string, entry: string, page: number, ta2Id: number, english: string, latin: string): AnatomyTerm => ({
  zh,
  source: `${MAINLAND_TERMS}#page=${page}`,
  sourceTerm: `大陆术语 ${entry}: ${zh} / ${english}; TA2 ${ta2Id}: ${english} / ${latin}`,
  note: "NAER 无该整体结构的可用对应行；已核对 FIPAT TA2 及复旦大学托管的《人体解剖学名词》参考副本，未宣称专业审校。",
});
const sourcedDirect = (zh: string, english: string, entry: string, page: number): AnatomyTerm => ({
  zh,
  source: `${MAINLAND_TERMS}#page=${page}`,
  sourceTerm: `${entry}: ${zh} / ${english}`,
  note: '已核对原文条目与图谱名称；属于来源对应核查，未宣称专业审校。',
});

/** Exact atlas-name cores whose correspondence was checked against the cited source row. */
export const EXISTING_ANATOMY_TERMS: Record<string, AnatomyTerm> = {
  "levator scapulae": sourcedDirect("肩胛提肌", "levator scapulae", "02.1514", 116),
  "serratus posterior inferior": sourcedDirect("下后锯肌", "serratus posterior inferior", "02.1515", 116),
  "serratus posterior superior": sourcedDirect("上后锯肌", "serratus posterior superior", "02.1516", 116),
  "iliocostalis thoracis": sourcedDirect("胸髂肋肌", "iliocostalis thoracis", "02.1522", 117),
  "longissimus thoracis": sourcedDirect("胸最长肌", "longissimus thoracis", "02.1525", 117),
  "longissimus cervicis": sourcedDirect("颈最长肌", "longissimus cervicis", "02.1526", 117),
  "spinalis thoracis": sourcedDirect("胸棘肌", "spinalis thoracis", "02.1529", 117),
  "semispinalis thoracis": sourcedDirect("胸半棘肌", "semispinalis thoracis", "02.1534", 117),
  "semispinalis capitis": sourcedDirect("头半棘肌", "semispinalis capitis", "02.1536", 118),
  "precentral gyrus": sourcedDirect("中央前回", "precentral gyrus", "06.0586", 339),
  "superior frontal gyrus": sourcedDirect("额上回", "superior frontal gyrus", "06.0588", 339),
  "middle frontal gyrus": sourcedDirect("额中回", "middle frontal gyrus", "06.0590", 339),
  "inferior frontal gyrus": sourcedDirect("额下回", "inferior frontal gyrus", "06.0591", 339),
  "postcentral gyrus": sourcedDirect("中央后回", "postcentral gyrus", "06.0598", 340),
  "superior parietal lobule": sourcedDirect("顶上小叶", "superior parietal lobule", "06.0600", 340),
  "supramarginal gyrus": sourcedDirect("缘上回", "supramarginal gyrus", "06.0603", 340),
  "angular gyrus": sourcedDirect("角回", "angular gyrus", "06.0604", 340),
  "occipital lobe": sourcedDirect("枕叶", "occipital lobe", "06.0605", 340),
  "middle temporal gyrus": sourcedDirect("颞中回", "middle temporal gyrus", "06.0613", 340),
  "inferior temporal gyrus": sourcedDirect("颞下回", "inferior temporal gyrus", "06.0614", 340),
  "cingulate gyrus": sourcedDirect("扣带回", "cingulate gyrus", "06.0626", 341),
  "lamina terminalis": sourcedDirect("终板", "lamina terminalis", "06.0634", 341),
  "longissimus capitis": { zh: "\u5934\u6700\u957f\u808c", source: NAER_DATASET, sourceTerm: "row 27: M. longissimus capitis — (頭最長肌)", note: simplifiedNote },
  atlas: { zh: "\u5bf0\u690e", source: NAER_DATASET, sourceTerm: "row 1569: Atlas — 寰椎；(第一頸椎)", note: "选用来源记录中的首个正式术语，并规范化字形。" },
  cerebellum: { zh: "\u5c0f\u8111", source: NAER_DATASET, sourceTerm: "row 1866: Cerebellum — 小腦", note: simplifiedNote },
  "conus elasticus": { zh: "\u5f39\u529b\u5706\u9525", source: NAER_DATASET, sourceTerm: "row 2016: Conus elasticus — 彈力圓錐", note: simplifiedNote },
  cornea: { zh: "\u89d2\u819c", source: NAER_DATASET, sourceTerm: "row 2028: Cornea — 角膜" },
  "corona ciliaris": { zh: "\u776b\u72b6\u51a0", source: NAER_DATASET, sourceTerm: "row 2032: Corona ciliaris — 睫狀冠", note: simplifiedNote },
  "corpus callosum": { zh: "\u80fc\u80dd\u4f53", source: NAER_DATASET, sourceTerm: "row 2046: Corpus callosum — 胼胝體", note: simplifiedNote },
  epididymis: { zh: "\u9644\u777e", source: NAER_DATASET, sourceTerm: "row 2381: Epididymis — \u9644\u776a", note: simplifiedNote },
  epiglottis: { zh: "\u4f1a\u538c", source: NAER_DATASET, sourceTerm: "row 2382: Epiglottis — 會厭", note: simplifiedNote },
  "glans penis": { zh: "\u9634\u830e\u5934", source: NAER_DATASET, sourceTerm: "row 2869: Glans penis — 陰莖頭；龜頭", note: "选用来源记录中的首个正式术语，并规范化字形。" },
  hypothalamus: { zh: "\u4e0b\u4e18\u8111", source: NAER_DATASET, sourceTerm: "row 2974: Hypothalamus — 丘腦下部", note: modernizedNote },
  insula: { zh: "\u8111\u5c9b", source: NAER_DATASET, sourceTerm: "row 3063: Insula — 島；腦島", note: "选用来源记录中解剖学专用的同义词，并规范化字形。" },
  iris: { zh: "\u8679\u819c", source: NAER_DATASET, sourceTerm: "row 3092: Iris — 虹膜" },
  "linea alba": { zh: "\u767d\u7ebf", source: NAER_DATASET, sourceTerm: "row 3386: Linea alba — 白線", note: simplifiedNote },
  "abductor hallucis": { zh: "\u62c7\u5c55\u808c", source: NAER_DATASET, sourceTerm: "row 3480: M. abductor hallucis — 外展拇肌", note: modernizedNote },
  "abductor pollicis brevis": { zh: "\u62c7\u77ed\u5c55\u808c", source: NAER_DATASET, sourceTerm: "row 3481: M. abductor pollicis brevis — 外展拇短肌", note: modernizedNote },
  "abductor pollicis longus": { zh: "\u62c7\u957f\u5c55\u808c", source: NAER_DATASET, sourceTerm: "row 3482: M. abductor pollicis longus — 外展拇長肌", note: modernizedNote },
  "adductor brevis": { zh: "\u77ed\u6536\u808c", source: NAER_DATASET, sourceTerm: "row 3483: M. adductor brevis — 內收短肌", note: modernizedNote },
  "adductor longus": { zh: "\u957f\u6536\u808c", source: NAER_DATASET, sourceTerm: "row 3485: M. adductor longus — 內收長肌", note: modernizedNote },
  "adductor magnus": { zh: "\u5927\u6536\u808c", source: NAER_DATASET, sourceTerm: "row 3486: M. adductor magnus — 內收大肌", note: modernizedNote },
  "adductor minimus": { zh: "\u5c0f\u6536\u808c", source: NAER_DATASET, sourceTerm: "row 3487: M. adductor minimus — 內收小肌", note: modernizedNote },
  aryepiglotticus: { zh: "\u6753\u4f1a\u538c\u808c", source: NAER_DATASET, sourceTerm: "row 3493: M. aryepiglotticus — 杓會厭肌", note: simplifiedNote },
  brachialis: { zh: "\u80b1\u808c", source: NAER_DATASET, sourceTerm: "row 3498: M. brachialis — 肱肌" },
  coracobrachialis: { zh: "\u5599\u80b1\u808c", source: NAER_DATASET, sourceTerm: "row 3507: M. coracobrachialis — 喙肱肌" },
  "extensor carpi radialis brevis": { zh: "\u6861\u4fa7\u8155\u77ed\u4f38\u808c", source: NAER_DATASET, sourceTerm: "row 3517: M. extensor carpi radialis brevis — 橈側伸腕短肌", note: modernizedNote },
  "extensor carpi radialis longus": { zh: "\u6861\u4fa7\u8155\u957f\u4f38\u808c", source: NAER_DATASET, sourceTerm: "row 3518: M. extensor carpi radialis longus — 橈側伸腕長肌", note: modernizedNote },
  "extensor carpi ulnaris": { zh: "\u5c3a\u4fa7\u8155\u4f38\u808c", source: NAER_DATASET, sourceTerm: "row 3519: M. extensor carpi ulnaris — 尺側伸腕肌", note: modernizedNote },
  "extensor digitorum longus": { zh: "\u8dbe\u957f\u4f38\u808c", source: NAER_DATASET, sourceTerm: "row 3523: M. extensor digitorum longus — 伸趾長肌", note: modernizedNote },
  "extensor hallucis brevis": { zh: "\u62c7\u77ed\u4f38\u808c", source: NAER_DATASET, sourceTerm: "row 3524: M. extensor hallucis brevis — 伸拇短肌", note: modernizedNote },
  "extensor hallucis longus": { zh: "\u62c7\u957f\u4f38\u808c", source: NAER_DATASET, sourceTerm: "row 3525: M. extensor hallucis longus — 伸拇長肌", note: modernizedNote },
  "extensor pollicis brevis": { zh: "\u62c7\u77ed\u4f38\u808c", source: NAER_DATASET, sourceTerm: "row 3527: M. extensor pollicis brevis — 伸拇短肌", note: modernizedNote },
  "extensor pollicis longus": { zh: "\u62c7\u957f\u4f38\u808c", source: NAER_DATASET, sourceTerm: "row 3528: M. extensor pollicis longus — 伸拇長肌", note: modernizedNote },
  "flexor carpi radialis": { zh: "\u6861\u4fa7\u8155\u5c48\u808c", source: NAER_DATASET, sourceTerm: "row 3529: M. flexor carpi radialis — 橈側屈腕肌", note: modernizedNote },
  "flexor digitorum brevis": { zh: "\u8dbe\u77ed\u5c48\u808c", source: NAER_DATASET, sourceTerm: "row 3532: M. flexor digitorum brevis — 屈趾短肌", note: modernizedNote },
  "flexor digitorum longus": { zh: "\u8dbe\u957f\u5c48\u808c", source: NAER_DATASET, sourceTerm: "row 3533: M. flexor digitorum longus — 屈趾長肌", note: modernizedNote },
  "flexor digitorum profundus": { zh: "\u6307\u6df1\u5c48\u808c", source: NAER_DATASET, sourceTerm: "row 3534: M. flexor digitorum profundus — 屈指深肌", note: modernizedNote },
  "flexor digitorum superficialis": { zh: "\u6307\u6d45\u5c48\u808c", source: NAER_DATASET, sourceTerm: "row 3535: M. flexor digitorum superficialis — 屈指淺肌", note: modernizedNote },
  "flexor hallucis longus": { zh: "\u62c7\u957f\u5c48\u808c", source: NAER_DATASET, sourceTerm: "row 3537: M. flexor hallucis longus — 屈拇長肌", note: modernizedNote },
  "flexor pollicis brevis": { zh: "\u62c7\u77ed\u5c48\u808c", source: NAER_DATASET, sourceTerm: "row 3538: M. flexor pollicis brevis — 屈拇短肌", note: modernizedNote },
  "flexor pollicis longus": { zh: "\u62c7\u957f\u5c48\u808c", source: NAER_DATASET, sourceTerm: "row 3539: M. flexor pollicis longus — 屈拇長肌", note: modernizedNote },
  genioglossus: { zh: "\u988f\u820c\u808c", source: NAER_DATASET, sourceTerm: "row 3543: M. genioglossus — 頦舌肌", note: simplifiedNote },
  gracilis: { zh: "\u80a1\u8584\u808c", source: NAER_DATASET, sourceTerm: "row 3549: M. gracilis — 股薄肌" },
  hyoglossus: { zh: "\u820c\u9aa8\u820c\u808c", source: NAER_DATASET, sourceTerm: "row 3552: M. hyoglossus — 舌骨舌肌" },
  "iliocostalis cervicis": { zh: "\u9888\u9ac2\u808b\u808c", source: NAER_DATASET, sourceTerm: "row 3555: M. iliocostalis cervicis — 項髂肋肌", note: modernizedNote },
  "iliocostalis lumborum": { zh: "\u8170\u9ac2\u808b\u808c", source: NAER_DATASET, sourceTerm: "row 3557: M. iliocostalis lumborum — 腰髂肋肌", note: simplifiedNote },
  "levator veli palatini": { zh: "\u816d\u5e06\u63d0\u808c", source: NAER_DATASET, sourceTerm: "row 3565: M. levator veli palatini — 提腭帆肌", note: modernizedNote },
  "longus capitis": { zh: "\u5934\u957f\u808c", source: NAER_DATASET, sourceTerm: "row 3568: M. longus capitis — 頭長肌", note: simplifiedNote },
  "obturator externus": { zh: "\u95ed\u5b54\u5916\u808c", source: NAER_DATASET, sourceTerm: "row 3578: M. obturator externus — 閉孔外肌", note: simplifiedNote },
  "obturator internus": { zh: "\u95ed\u5b54\u5185\u808c", source: NAER_DATASET, sourceTerm: "row 3579: M. obturator internus — 閉孔內肌", note: simplifiedNote },
  "opponens pollicis": { zh: "\u62c7\u5bf9\u638c\u808c", source: NAER_DATASET, sourceTerm: "row 3583: M. opponens pollicis — 拇指對掌肌", note: modernizedNote },
  "palmaris longus": { zh: "\u638c\u957f\u808c", source: NAER_DATASET, sourceTerm: "row 3589: M. palmaris longus — 掌長肌", note: simplifiedNote },
  pectineus: { zh: "\u803b\u9aa8\u808c", source: NAER_DATASET, sourceTerm: "row 3593: M. pectineus — 恥骨肌", note: simplifiedNote },
  "pectoralis minor": { zh: "\u80f8\u5c0f\u808c", source: NAER_DATASET, sourceTerm: "row 3595: M. pectoralis minor — 胸小肌" },
  piriformis: { zh: "\u68a8\u72b6\u808c", source: NAER_DATASET, sourceTerm: "row 3597: M. piriformis — 梨狀肌", note: simplifiedNote },
  plantaris: { zh: "\u8dd6\u808c", source: NAER_DATASET, sourceTerm: "row 3598: M. plantaris — 蹠肌", note: simplifiedNote },
  popliteus: { zh: "\u8158\u808c", source: NAER_DATASET, sourceTerm: "row 3600: M. popliteus — 膕肌", note: simplifiedNote },
  "pronator quadratus": { zh: "\u65cb\u524d\u65b9\u808c", source: NAER_DATASET, sourceTerm: "row 3601: M. pronator quadratus — 旋前方肌" },
  "psoas major": { zh: "\u8170\u5927\u808c", source: NAER_DATASET, sourceTerm: "row 3604: M. psoas major — 腰大肌" },
  "quadratus femoris": { zh: "\u80a1\u65b9\u808c", source: NAER_DATASET, sourceTerm: "row 3609: M. quadratus femoris — 股方肌" },
  "rectus capitis lateralis": { zh: "\u5934\u5916\u4fa7\u76f4\u808c", source: NAER_DATASET, sourceTerm: "row 3617: M. rectus capitis lateralis — 頭外側直肌", note: simplifiedNote },
  sartorius: { zh: "\u7f1d\u5320\u808c", source: NAER_DATASET, sourceTerm: "row 3622: M. sartorius — 縫匠肌", note: simplifiedNote },
  "scalenus medius": { zh: "\u4e2d\u659c\u89d2\u808c", source: NAER_DATASET, sourceTerm: "row 3623: M. scalenus medius — 中斜角肌" },
  "semispinalis cervicis": { zh: "\u9888\u534a\u68d8\u808c", source: NAER_DATASET, sourceTerm: "row 3626: M. semispinalis cervicis — 項半棘肌", note: modernizedNote },
  spinalis: { zh: "\u68d8\u808c", source: NAER_DATASET, sourceTerm: "row 3636: M. spinalis — 棘肌" },
  "splenius capitis": { zh: "\u5934\u5939\u808c", source: NAER_DATASET, sourceTerm: "row 3641: M. splenius capitis — 頭夾肌", note: simplifiedNote },
  "splenius cervicis": { zh: "\u9888\u5939\u808c", source: NAER_DATASET, sourceTerm: "row 3642: M. splenius cervicis — 頸夾肌", note: simplifiedNote },
  subclavius: { zh: "\u9501\u9aa8\u4e0b\u808c", source: NAER_DATASET, sourceTerm: "row 3650: M. subclavius — 鎖骨下肌", note: simplifiedNote },
  subscapularis: { zh: "\u80a9\u80db\u4e0b\u808c", source: NAER_DATASET, sourceTerm: "row 3651: M. subscapularis — 肩胛下肌" },
  supinator: { zh: "\u65cb\u540e\u808c", source: NAER_DATASET, sourceTerm: "row 3652: M. supinator — 旋後肌", note: simplifiedNote },
  "tensor veli palatini": { zh: "\u816d\u5e06\u5f20\u808c", source: NAER_DATASET, sourceTerm: "row 3657: M. tensor veli palatini — 張腭帆肌", note: modernizedNote },
  "teres major": { zh: "\u5927\u5706\u808c", source: NAER_DATASET, sourceTerm: "row 3658: M. teres major — 大圓肌", note: simplifiedNote },
  "teres minor": { zh: "\u5c0f\u5706\u808c", source: NAER_DATASET, sourceTerm: "row 3659: M. teres minor — 小圓肌", note: simplifiedNote },
  "transversus thoracis": { zh: "\u80f8\u6a2a\u808c", source: NAER_DATASET, sourceTerm: "row 3673: M. transversus thoracis — 胸橫肌", note: simplifiedNote },
  "vastus intermedius": { zh: "\u80a1\u4e2d\u95f4\u808c", source: NAER_DATASET, sourceTerm: "row 3680: M. vastus intermedius — 股中間肌", note: simplifiedNote },
  maxilla: { zh: "\u4e0a\u988c\u9aa8", source: NAER_DATASET, sourceTerm: "row 3748: Maxilla — 上頜骨", note: simplifiedNote },
  "medulla oblongata": { zh: "\u5ef6\u9ad3", source: NAER_DATASET, sourceTerm: "row 3765: Medulla oblongata — 延髓" },
  platysma: { zh: "\u9888\u9614\u808c", source: "https://www.imaios.cn/cn/e-anatomy/anatomical-structures/platysma-1541115436", sourceTerm: "Platysma / \u9888\u9614\u808c", note: "中国大陆术语确认；NAER row 4426 记录为 Platysma — 闊肌(頸)。" },
  pons: { zh: "\u6865\u8111", source: NAER_DATASET, sourceTerm: "row 4584: Pons — 橋腦", note: simplifiedNote },
  sclera: { zh: "\u5de9\u819c", source: NAER_DATASET, sourceTerm: "row 5190: Sclera — 鞏膜", note: simplifiedNote },
  "stria terminalis": { zh: "\u7ec8\u7eb9", source: NAER_DATASET, sourceTerm: "row 5408: Stria terminalis — 終紋", note: simplifiedNote },
  "tentorium cerebelli": { zh: "\u5c0f\u8111\u5e55", source: NAER_DATASET, sourceTerm: "row 5654: Tentorium cerebelli — 小腦幕", note: simplifiedNote },
  testis: { zh: "\u777e\u4e38", source: NAER_DATASET, sourceTerm: "row 5660: Testis — 睪丸", note: simplifiedNote },
  thalamus: { zh: "\u4e18\u8111", source: NAER_DATASET, sourceTerm: "row 5663: Thalamus — 丘腦", note: simplifiedNote },
  "tuber cinereum": { zh: "\u7070\u7ed3\u8282", source: NAER_DATASET, sourceTerm: "row 5790: Tuber cinereum — 灰結節", note: simplifiedNote },
  vomer: { zh: "\u7281\u9aa8", source: NAER_DATASET, sourceTerm: "row 6125: Vomer — 犂骨", note: simplifiedNote },
  "parietal bone": bridged("顶骨", 504, "parietal bone", "os parietale", 4132, "頂骨"),
  "frontal bone": bridged("额骨", 520, "frontal bone", "os frontale", 4115, "額骨"),
  "occipital bone": bridged("枕骨", 552, "occipital bone", "os occipitale", 4130, "枕骨"),
  "temporal bone": bridged("颞骨", 641, "temporal bone", "os temporale", 4138, "顳骨"),
  "lacrimal bone": bridged("泪骨", 744, "lacrimal bone", "os lacrimale", 4121, "淚骨"),
  "nasal bone": bridged("鼻骨", 748, "nasal bone", "os nasale", 4127, "鼻骨"),
  "palatine bone": bridged("腭骨", 798, "palatine bone", "os palatinum", 4131, "腭骨；口蓋骨"),
  "zygomatic bone": bridged("颧骨", 818, "zygomatic bone", "os zygomaticum", 4140, "顴骨"),
  "corniculate cartilage": bridged("小角状软骨", 997, "corniculate cartilage", "cartilago corniculata", 1815, "小角狀軟骨"),
  "cuneiform cartilage": bridged("楔状软骨", 998, "cuneiform cartilage", "cartilago cuneiformis", 1818, "楔狀軟骨"),
  "stylohyoid ligament": bridged("茎突舌骨韧带", 1567, "stylohyoid ligament", "ligamentum stylohyoideum", 3304, "莖突舌骨韌帶"),
  "vocal ligament": bridged("声韧带", 1661, "vocal ligament", "ligamentum vocale", 3325, "聲韌帶"),
  "long plantar ligament": bridged("足底长韧带", 1934, "long plantar ligament", "ligamentum plantare longum", 3292, "蹠側長韌帶"),
  "common tendinous ring": bridged("总腱环", 2047, "common tendinous ring", "anulus tendineus communis", 1402, "腱總環"),
  sternocleidomastoid: bridged("胸锁乳突肌", 2156, "sternocleidomastoid muscle", "musculus sternocleidomastoideus", 3644, "胸骨乳突肌"),
  stylohyoid: bridged("茎突舌骨肌", 2164, "stylohyoid muscle", "musculus stylohyoideus", 3648, "莖突舌骨肌"),
  mylohyoid: bridged("下颌舌骨肌", 2165, "mylohyoid muscle", "musculus mylohyoideus", 3573, "下頜舌骨肌"),
  geniohyoid: bridged("颏舌骨肌", 2166, "geniohyoid muscle", "musculus geniohyoideus", 3544, "頦舌骨肌"),
  sternohyoid: bridged("胸骨舌骨肌", 2168, "sternohyoid muscle", "musculus sternohyoideus", 3645, "胸舌骨肌"),
  omohyoid: bridged("肩胛舌骨肌", 2169, "omohyoid muscle", "musculus omohyoideus", 3581, "肩胛舌骨肌"),
  sternothyroid: bridged("胸骨甲状肌", 2173, "sternothyroid muscle", "musculus sternothyreoideus", 3646, "胸骨甲狀肌"),
  thyrohyoid: bridged("甲状舌骨肌", 2174, "thyrohyoid muscle", "musculus thyreohyoideus", 3662, "甲舌骨肌"),
  "external anal sphincter": bridged("肛门外括约肌", 2426, "external anal sphincter", "sphincter externus ani", 3631, "肛門外括約肌"),
  "fibularis tertius": bridged("腓骨第三肌", 2649, "fibularis tertius muscle", "musculus fibularis tertius", 624, "腓骨第三肌"),
  "fibularis longus": bridged("腓骨长肌", 2652, "fibularis longus muscle", "musculus fibularis longus", 623, "腓骨長肌"),
  "fibularis brevis": bridged("腓骨短肌", 2653, "fibularis brevis muscle", "musculus fibularis brevis", 622, "腓骨短肌"),
  tongue: bridged("舌", 2820, "tongue", "lingua", 3415, "舌"),
  "cystic duct": bridged("胆囊管", 3101, "cystic duct", "ductus cysticus", 2319, "膽囊管"),
  prostate: bridged("前列腺", 3637, "prostate", "prostata", 4680, "前列腺"),
  "corpus cavernosum of penis": bridged("阴茎海绵体", 3678, "corpus cavernosum of penis", "corpus cavernosum penis", 2049, "陰莖海綿體"),
  "coronary sinus": bridged("冠状窦", 4158, "coronary sinus", "sinus coronarius", 5257, "冠狀竇"),
  "descending aorta": bridged("降主动脉", 4185, "descending aorta", "aorta descendens", 1410, "降主動脈"),
  "subcostal artery": bridged("肋下动脉", 4202, "subcostal artery", "arteria subcostalis", 1245, "肋下動脈"),
  "common hepatic artery": bridged("肝总动脉", 4214, "common hepatic artery", "arteria hepatica communis", 224, "肝總動脈"),
  "splenic artery": bridged("脾动脉", 4239, "splenic artery", "arteria splenica", 1205, "脾動脈"),
  "appendicular artery": bridged("阑尾动脉", 4261, "appendicular artery", "arteria appendicularis", 1134, "闌尾動脈"),
  "middle colic artery": bridged("中结肠动脉", 4265, "middle colic artery", "arteria colica media", 1164, "中結腸動脈"),
  "testicular artery": bridged("睾丸动脉", 4288, "testicular artery", "arteria testicularis", 1253, "睪丸動脈"),
  "dorsal artery of penis": bridged("阴茎背动脉", 4354, "dorsal artery of penis", "arteria dorsalis penis", 1177, "陰莖背動脈"),
  "ophthalmic artery": bridged("眼动脉", 4469, "ophthalmic artery", "arteria ophthalmica", 1216, "眼動脈"),
  "anterior communicating artery": bridged("前交通动脉", 4517, "anterior communicating artery", "arteria communicans anterior", 1169, "前交通動脈"),
  "posterior communicating artery": bridged("后交通动脉", 4521, "posterior communicating artery", "arteria communicans posterior", 1170, "後交通動脈"),
  "subclavian artery": bridged("锁骨下动脉", 4537, "subclavian artery", "arteria subclavia", 1244, "鎖骨下動脈"),
  "vertebral artery": bridged("椎动脉", 4538, "vertebral artery", "arteria vertebralis", 1270, "椎動脈"),
  "internal thoracic artery": bridged("胸廓内动脉", 4576, "internal thoracic artery", "arteria thoracica interna", 1254, "胸廓內動脈"),
  "axillary artery": bridged("腋动脉", 4616, "axillary artery", "arteria axillaris", 1137, "腋動脈"),
  "subscapular artery": bridged("肩胛下动脉", 4627, "subscapular artery", "arteria subscapularis", 1248, "肩胛下動脈"),
  "deep brachial artery": bridged("肱深动脉", 4634, "deep brachial artery", "arteria profunda brachii", 1230, "肱深動脈"),
  "radial recurrent artery": bridged("桡返动脉", 4642, "radial recurrent artery", "arteria recurrens radialis", 1238, "橈返動脈"),
  "internal jugular vein": bridged("颈内静脉", 4800, "internal jugular vein", "vena jugularis interna", 6071, "頸內靜脈"),
  "subclavian vein": bridged("锁骨下静脉", 4953, "subclavian vein", "vena subclavia", 6076, "鎖骨下靜脈"),
  "axillary vein": bridged("腋静脉", 4963, "axillary vein", "vena axillaris", 6063, "腋靜脈"),
  "cephalic vein": bridged("头静脉", 4964, "cephalic vein", "vena cephalica", 6065, "頭靜脈"),
  "median cubital vein": bridged("肘正中静脉", 4980, "median cubital vein", "vena mediana cubiti", 5935, "肘正中靜脈"),
  "median antebrachial vein": bridged("前臂正中静脉", 4981, "median antebrachial vein", "vena mediana antebrachii", 6072, "前臂正中靜脈"),
  "great saphenous vein": bridged("大隐静脉", 5058, "great saphenous vein", "vena saphena magna", 5942, "大隱靜脈"),
  "small saphenous vein": bridged("小隐静脉", 5085, "small saphenous vein", "vena saphena parva", 5943, "小隱靜脈"),
  "caudate nucleus": bridged("尾状核", 5561, "caudate nucleus", "nucleus caudatus", 4036, "尾狀核"),
  "lateral geniculate body": bridged("外侧膝状体", 5666, "lateral geniculate body", "corpus geniculatum laterale", 2058, "外側膝狀體"),
  "medial geniculate body": bridged("内侧膝状体", 5667, "medial geniculate body", "corpus geniculatum mediale", 2059, "內側膝狀體"),
  midbrain: bridged("中脑", 5874, "midbrain", "mesencephalon", 3790, "中腦"),
  "trochlear nerve": bridged("滑车神经", 6191, "trochlear nerve", "nervus trochlearis", 3983, "滑車神經"),
  "ophthalmic nerve": bridged("眼神经", 6196, "ophthalmic nerve", "nervus ophthalmicus", 3980, "眼神經"),
  "frontal nerve": bridged("额神经", 6199, "frontal nerve", "nervus frontalis", 3899, "額神經"),
  "supratrochlear nerve": bridged("滑车上神经", 6203, "supratrochlear nerve", "nervus supratrochlearis", 3946, "滑車上神經"),
  "posterior ethmoidal nerve": bridged("筛后神经", 6207, "posterior ethmoidal nerve", "nervus ethmoideus posterior", 3897, "篩後神經"),
  "anterior ethmoidal nerve": bridged("筛前神经", 6208, "anterior ethmoidal nerve", "nervus ethmoideus anterior", 3896, "篩前神經"),
  "infratrochlear nerve": bridged("滑车下神经", 6214, "infratrochlear nerve", "nervus infratrochlearis", 3905, "滑車下神經"),
  "ciliary ganglion": bridged("睫状神经节", 6663, "ciliary ganglion", "ganglion ciliare", 2819, "睫狀神經節"),
  "vitreous body": bridged("玻璃体", 6809, "vitreous body", "corpus vitreum", 2095, "玻璃狀體"),
  "lacrimal sac": bridged("泪囊", 6857, "lacrimal sac", "saccus lacrimalis", 5169, "淚囊"),
  "nasolacrimal duct": bridged("鼻泪管", 6859, "nasolacrimal duct", "ductus nasolacrimalis", 2330, "鼻淚管"),
  "external ear": bridged("外耳", 6862, "external ear", "auris externa", 1580, "外耳"),
  choroid: bridged("脉络膜", 6774, "choroid", "chorioidea", 1881, "脈絡膜"),
  "lacrimal canaliculus": mainlandBridged("泪小管", "07.0146", 390, 6855, "lacrimal canaliculus", "canaliculus lacrimalis", 2312, "Ductuli lacrimales", "淚管"),
  "lacrimal gland": mainlandDirect("泪腺", "07.0137", 390, 6846, "lacrimal gland", "glandula lacrimalis"),
  "lacrimal lake": mainlandBridged("泪湖", "07.0143", 390, 6852, "lacrimal lake", "lacus lacrimalis", 3141, "Lacus lacrimalis", "淚湖"),
  lens: bridged("晶状体", 6798, "lens", "lens", 3219, "晶狀體"),
  "inferior oblique": mainlandBridged("下斜肌", "07.0099", 388, 2051, "inferior oblique muscle", "musculus obliquus inferior bulbi oculi", 630, "*M. obliquus bulbi inferior", "眼球下斜肌"),
  "inferior rectus": mainlandBridged("下直肌", "07.0093", 388, 2043, "inferior rectus muscle", "musculus rectus inferior", 637, "*M. rectus bulbi inferior", "眼球下直肌"),
  "lateral rectus": mainlandBridged("外直肌", "07.0095", 388, 2045, "lateral rectus muscle", "musculus rectus lateralis bulbi oculi", 640, "*M. rectus bulbi temporalis", "眼球顬側直肌"),
  "levator palpebrae superioris": mainlandBridged("上睑提肌", "07.0100", 388, 2052, "levator palpebrae superioris", "levator palpebrae superioris", 3563, "M. levator palpebræ superioris", "提上瞼肌"),
  "medial rectus": mainlandBridged("内直肌", "07.0094", 388, 2044, "medial rectus muscle", "musculus rectus medialis", 638, "*M. rectus bulbi nasalis", "眼球鼻側直肌"),
  "superior oblique": mainlandBridged("上斜肌", "07.0097", 388, 2048, "superior oblique muscle", "musculus obliquus superior bulbi oculi", 631, "*M. obliquus bulbi superior", "眼球上斜肌"),
  "superior rectus": mainlandBridged("上直肌", "07.0092", 388, 2042, "superior rectus muscle", "musculus rectus superior", 639, "*M. rectus bulbi superior", "眼球上直肌"),
  "lacrimal nerve": bridged("泪腺神经", 6198, "lacrimal nerve", "nervus lacrimalis", 3911, "淚腺神經"),
  "nasociliary nerve": mainlandBridged("鼻睫神经", "06.1061", 367, 6204, "nasociliary nerve", "nervus nasociliaris", 3922, "N. nasociliaris", "鼻睫[狀]神經"),
  "optic nerve": mainlandDirect("视神经", "06.1032", 366, 6183, "optic nerve", "nervus opticus"),
  "long ciliary nerve": mainlandBridged("睫状长神经", "06.1063", 368, 6206, "long ciliary nerves", "nervi ciliares longi", 3994, "Nn. ciliares longi", "睫狀長神經"),
  "short ciliary nerve": mainlandBridged("睫状短神经", "06.1048", 367, 6664, "short ciliary nerves", "nervi ciliares breves", 3993, "Nn. ciliares breves", "睫狀短神經"),
  "supra-orbital nerve": mainlandDirect("眶上神经", "06.1059", 367, 6200, "supra-orbital nerve", "nervus supraorbitalis"),
  "flexor accessorius": mainlandBridged("足底方肌", "02.1799", 133, 2684, "flexor accessorius muscle", "flexor accessorius", 3611, "M. quadratus plantæ", "蹠方肌"),
  "gemellus inferior": mainlandBridged("下孖肌", "02.1747", 130, 2607, "inferior gemellus muscle", "musculus gemellus inferior", 626, "*M. gemellus tuberalis", "孖結節肌"),
  "gemellus superior": mainlandBridged("上孖肌", "02.1746", 130, 2606, "superior gemellus muscle", "musculus gemellus superior", 625, "*M. gemellus spinalis", "孖棘肌"),
  "gluteus maximus": bridged("臀大肌", 2598, "gluteus maximus muscle", "musculus gluteus maximus", 3546, "臀大肌"),
  "gluteus medius": bridged("臀中肌", 2599, "gluteus medius muscle", "musculus gluteus medius", 3547, "臀中肌"),
  "gluteus minimus": bridged("臀小肌", 2600, "gluteus minimus muscle", "musculus gluteus minimus", 3548, "臀小肌"),
  iliacus: bridged("髂肌", 2594, "iliacus muscle", "musculus iliacus", 3553, "髂肌"),
  semimembranosus: bridged("半膜肌", 2642, "semimembranosus muscle", "musculus semimembranosus", 3624, "半膜肌"),
  semitendinosus: bridged("半腱肌", 2641, "semitendinosus muscle", "musculus semitendinosus", 3628, "半腱肌"),
};

export const ANATOMY_TERMS: Record<string, AnatomyTerm> = {
  ...EXISTING_ANATOMY_TERMS,
  ...FUDAN_BATCH_1_TERMS,
};
